package crm.libraries.abm.entities;
// Generated 29/07/2013 17:57:36 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import java.util.Vector;

/**
 * InvDepositos generated by hbm2java
 */
public class Depositos  implements ABMEntity {


     private String codigo;
     private String depDescripcion;
     private Boolean depActivo;

    public Depositos() {
    }

	
    public Depositos(String depDescripcion, Boolean depActivo) {
        this.depDescripcion = depDescripcion;
        this.depActivo = depActivo;
    }

    public String getDepDescripcion() {
        return this.depDescripcion;
    }
    
    public void setDepDescripcion(String depDescripcion) {
        this.depDescripcion = depDescripcion;
    }
    public Boolean isDepActivo() {
        return this.depActivo;
    }
    
    public void setDepActivo(Boolean depActivo) {
        this.depActivo = depActivo;
    }


	public String getCodigo() {
		// TODO Auto-generated method stub
		return codigo;
	}


	public void setCodigo(String codigo) {
		// TODO Auto-generated method stub
		this.codigo=codigo;
	}


	public Vector toVector() {
		// TODO Auto-generated method stub
		return null;
	}
	
	public String toString(){
		return depDescripcion;
	}

}


