package crm.libraries.abm.entities;
// Generated 29/07/2013 17:57:36 by Hibernate Tools 3.2.1.GA

import java.util.Vector;




/**
 * InvEquipos generated by hbm2java
 */
public class Equipos implements ABMEntity  {


     //private Integer eqIdequipo;
	 private String codigo;
     private String invDepositos;
     private String invEquiposFamilias;
     private String eqDescripcion;
     private String eqNroserie;
     private String eqActivo;
     private String observaciones;
     private String eqEstado;
     private String codigoBarras;
     private String modelo;
     private int alto;
     private int ancho;
     private int largo;
     private int peso;

    public int getAlto() {
		return alto;
	}

	public void setAlto(int alto) {
		this.alto = alto;
	}

	public int getAncho() {
		return ancho;
	}

	public void setAncho(int ancho) {
		this.ancho = ancho;
	}

	public int getLargo() {
		return largo;
	}

	public void setLargo(int largo) {
		this.largo = largo;
	}

	public int getPeso() {
		return peso;
	}

	public void setPeso(int peso) {
		this.peso = peso;
	}

	public String getModelo() {
        return modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public String getCodigoBarras() {
		return codigoBarras;
	}

	public void setCodigoBarras(String codigoBarras) {
		this.codigoBarras = codigoBarras;
	}

	public String getEqEstado() {
		return eqEstado;
	}

	public void setEqEstado(String eqEstado) {
		this.eqEstado = eqEstado;
	}

	public String getObservaciones() {
		return observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Equipos() {
    	eqActivo="S";
    }

    public Equipos(String invDepositos, String invEquiposFamilias, String eqDescripcion, String eqNroserie, String eqActivo, String model) {
       super();
    	this.invDepositos = invDepositos;
       this.invEquiposFamilias = invEquiposFamilias;
       this.eqDescripcion = eqDescripcion;
       this.eqNroserie = eqNroserie;
       this.eqActivo = eqActivo;
       this.modelo = model;
    }
   
    /*public Integer getEqIdequipo() {
        return this.eqIdequipo;
    }
    
    public void setEqIdequipo(Integer eqIdequipo) {
        this.eqIdequipo = eqIdequipo;
    }*/
    public String getInvDepositos() {
        return this.invDepositos;
    }
    
    public void setInvDepositos(String invDepositos) {
        this.invDepositos = invDepositos;
    }
    public String getInvEquiposFamilias() {
        return this.invEquiposFamilias;
    }
    
    public void setInvEquiposFamilias(String invEquiposFamilias) {
        this.invEquiposFamilias = invEquiposFamilias;
    }
    public String getEqDescripcion() {
        return this.eqDescripcion;
    }
    
    public void setEqDescripcion(String eqDescripcion) {
        this.eqDescripcion = eqDescripcion;
    }
    public String getEqNroserie() {
        return this.eqNroserie;
    }
    
    public void setEqNroserie(String eqNroserie) {
        this.eqNroserie = eqNroserie;
    }
    public String getEqActivo() {
        return this.eqActivo;
    }
    
    public void setEqActivo(String eqActivo) {
        this.eqActivo = eqActivo;
    }

    public void setCodigo(String codigo) {
        this.codigo=codigo;
    }

    public String getCodigo() {
        return codigo;
    }

    public Vector toVector() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public String toString(){
		return eqDescripcion;
	}
    
}


