package crm.libraries.abm.entities;
// Generated 29/07/2013 17:57:36 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import java.util.Vector;

/**
 * InvEquiposFamilias generated by hbm2java
 */
public class EquiposFamilias implements ABMEntity{


     private String codigo;
     private String eqfamDescripcion;
     private boolean eqfamActivo;

    public EquiposFamilias() {
    }

	
    public EquiposFamilias(String eqfamDescripcion, boolean eqfamActivo) {
        this.eqfamDescripcion = eqfamDescripcion;
        this.eqfamActivo = eqfamActivo;
    }

    public String getEqfamDescripcion() {
        return this.eqfamDescripcion;
    }
    
    public void setEqfamDescripcion(String eqfamDescripcion) {
        this.eqfamDescripcion = eqfamDescripcion;
    }
    public boolean isEqfamActivo() {
        return this.eqfamActivo;
    }
    
    public void setEqfamActivo(boolean eqfamActivo) {
        this.eqfamActivo = eqfamActivo;
    }

	public String getCodigo() {
		// TODO Auto-generated method stub
		return codigo;
	}


	public void setCodigo(String codigo) {
		this.codigo=codigo;
		
	}


	public Vector toVector() {
		// TODO Auto-generated method stub
		return null;
	}

	public String toString(){
		return eqfamDescripcion;
	}


}


